#!/bin/sh -e
# Debconf interface, see debconf-devel(7) for details.
# Written by Joachim Nilsson <joachim!nilsson()member!fsf!org>

# Source debconf library.
. /usr/share/debconf/confmodule

# Setup default values
USERNAME=""
PASSWORD=""
LOGIN_SERVER="10.0.0.6"

# Set title
db_title "GNU Alive Configuration"

# Pop the question...
db_input medium alive/use_debconf_question || true
db_go || true
db_get alive/use_debconf_question
if [ "$RET" == "true" ]; then
    if [ -f /etc/qadsl.conf ]; then
        db_input medium alive/reuse_qadsl_conf_values_question || true
        db_go || true
        db_get alive/reuse_qadsl_conf_values_question
        $REUSE=$RET
        db_fget alive/reuse_qadsl_conf_values_question seen
        if [ "$RET" == "false" -a "$REUSE" == "true" ]; then
            # Get current settings
            . /etc/qadsl.conf
            # User freedom sometimes sucks...
            if [ "$USER" != "" ]; then
                USERNAME=$USER
            fi
            if [ "$PASS" != "" ]; then
                PASSWORD=$PASS
            fi
            if [ "$SERV" != "" ]; then
                LOGIN_SERVER=$SERV
            fi
            if [ "$SERVER" != "" ]; then
                LOGIN_SERVER=$SERVER
            fi
        fi
    fi

    db_set alive/login_server_question $LOGIN_SERVER
    db_set alive/username_question $USERNAME
    db_set alive/password_question $PASSWORD

    db_beginblock
    db_input medium alive/login_server_question || true
    db_input medium alive/username_question || true
    db_input medium alive/password_question || true
    db_endblock

    db_go || true
fi
